# Generated by Django 3.2.4 on 2021-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('description_short', models.TextField(verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('coordinates_lng', models.FloatField(verbose_name='Долгота')),
                ('coordinates_lat', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Интересное место города',
                'verbose_name_plural': 'Интересные места города',
                'ordering': ('title',),
            },
        ),
    ]
