# Generated by Django 3.2.4 on 2021-06-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.TextField(max_length=128, verbose_name='id места'),
        ),
    ]
