# Generated by Django 3.2.4 on 2021-06-30 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядковый номер'),
        ),
    ]
