# Generated by Django 3.1 on 2022-04-22 06:54

from django.db import migrations
from places.utils import slugify


def gen_slug(apps, schema_editor):
    Place = apps.get_model("places", "Place")
    for row in Place.objects.all():
        row.slug = slugify(row.title)
        row.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0011_auto_20220422_1634"),
    ]

    operations = [
        migrations.RunPython(gen_slug, reverse_code=migrations.RunPython.noop),
    ]
