# Generated by Django 3.1 on 2022-04-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20220422_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order_num',
            field=models.PositiveIntegerField(blank=True, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place'),
        ),
    ]
