# Generated by Django 3.1 on 2022-04-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_auto_20220422_1824'),
        ('places', '0014_auto_20220422_2200'),
    ]

    operations = [
    ]
